[package]
name = "debentures-hack-meridian"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.5.0"

[dev-dependencies]
soroban-sdk = { version = "21.5.0", features = ["testutils"] }
